### ISSUE TITLE
[Request] Adding ability to call .NET framework namespaces / Python packages

### ISSUE THREAD

**Issue by wbadry** [larics/Petri.Net#1]
Hi,
I'm very impressed with the functionality of Petri.NET simulator. It opens the door to new level of utilization of this functionality with hardware like Arduino and PLCs.

Is it possible to add functionality to use python packages like pyserial?
Is it also possible to use System.IO.Ports SerialPort class?

By using those two methods, simulator can be turned into logic controller with the aid of Arduino. I can assist in building example code for both languages. However, I don't know how to import such a package / class into editor.

Do you use **Python for .NET** as the backend of your editor?

**Comment by isindicic** [comment]
For Python extension libraries, all libraries should be located in "lib" and "DLLs" directories. If you take a look at those location you'll notice a lot of already available libraries that can be used with Python in Petri.NET.  I'm not familiar with that library but I suppose pyserial library files should be copied there too and then will become available. I can try to do that for some future release.

However, serial port classes can be used from C#  scripting ... In following example we open COM1 and send information about number of tokens in place P2 to COM1.

``` C#
//C#
System.IO.Ports.SerialPort sp = null;
public void Step(int k)
{
    if(sp == null)
    {
       sp = new System.IO.Ports.SerialPort();
       sp.PortName = "COM1";
       sp.BaudRate = 9600;
       sp.Parity = System.IO.Ports.Parity.None;
       sp.DataBits = 8;
       sp.StopBits = System.IO.Ports.StopBits.One;
       sp.Open();
       Print("Open COM port\n");
    } 

    Place p = FindPlace("P2");
    Print("P2 has " + p.Tokens + " tokens\n");

    sp.Write("P2 has " + p.Tokens + " tokens\r\n");

}

public void Reset()
{
    if(sp != null && sp.IsOpen)
    {
       Print("Close com port\n");
       sp.Close();
       sp = null;
    }
}
```

**Comment by wbadry** [comment]
Thanks for your response. Can I load Python package if I chose Python like pyFirmata if I chose Python instead?

**Comment by isindicic** [comment]
OK.. I take a look at pyserial and it require python 2.7 or newer (which is a problem as I use version 2.6 because of .NET 2.0). 

However you can load and import whatever package you want, but that package must be available under lib and DLLs directory.. Few seconds ago I updated zip file with latest release. Those zip now include ipy.exe (IronPython shell) so you can play with it (and try to install packages)..

**Comment by isindicic** [comment]
I'll mark this issue closed. Following actions were performed:
- For python scripting I added ipy.exe (IronPython 2.6 command line) to distribution to allow installation of python packages.
- For C# scripting I add possibility to [include references to external libraries](https://github.com/larics/Petri.Net/wiki/15.Using-C#)

**Comment by wbadry** [comment]
Thanks for all your effort today. I talked a lot about your project to my students today 😃 . I used it for building DES for stamping machine simulation using 2 cylinders. I'll share it with you once finished. Thanks again. I owe you 😄
