### ISSUE TITLE
[Feature Request] Extend Wiki for an example to install external library on Pyhton

### ISSUE THREAD

**Issue by wbadry** [larics/Petri.Net#3]
Since wiki is concrete in demonstrating utilization of the simulator with python/C#, it would be great to show how to port any external python module and using it like pySerial or pyFirmata or any other library not shipped with it.

The problem lies in installation of external module requires **setuptools** which are not shipped.

**Comment by isindicic** [comment]
I updated release zip with full Python library .. Using ipy.exe I now successfully installed pyserial for Python 2.6 (pyserial is included in release zip so you can try it immediately).. Method is simple. I unpacked pyserial zip on same directory level, then go inside that directory and open command prompt.

Then I start **..\ipy.exe setup.py install** and package was successfully installed (at least they said it is :))

Similar method should be used with other packages. You'll only have to remember that we use Python 2.6 here so packages must be compatible with that.

I'll update wiki with that new informations when I catch some time ..

**Comment by wbadry** [comment]
Thanks Dr. Sindicic for your support again. I found pySerial as mentioned. However, when trying to install pyFirmata , **mstools** is still missing.
![](http://i.giphy.com/3oz8xVnQuFTnA1SpTG.gif)
Is there any mean:
- Upgrade .NET framework to 4.x or higher?
- Upgrade ipy to latest version

**Comment by isindicic** [comment]
On release page you'll find zip with simulator compiled with latest version of IronPython, its associated libraries and NET 4.0...  Hope it will help ..

**Comment by isindicic** [comment]
I tried to install pyFirmata using new IronPython but unfortunately I got same error. It seems that those module simply don't supposed to work with IronPython..  :-(

However, I find one that look fine on https://github.com/thutch/sharpduino (a .NET library for controlling an Arduino through the firmata protocol) and there are two IronPython samples .. . 

Look as those can be used with IronPython or even C# scripting from PN simulator

**Comment by wbadry** [comment]
@isindicic I already tried sharpduino from C# Console application yesterday before posting. That's why I asked to upgrade to .NET framework 4.x as it didn't compile on .NET 2.0. I overlooked it works on IronPython 😄 . Thanks for directing me 👍 .

I'm very grateful Dr. Sindicic for your consistent support to recurring my requests. A true raw model of researcher.

**Comment by isindicic** [comment]
Added [note how to install Python extensions/libraries](https://github.com/larics/Petri.Net/wiki/14.Using-Python) into wiki.
