### ISSUE TITLE
Tokens value not updated "Python"

### ISSUE THREAD

**Issue by wbadry** [larics/Petri.Net#4]
Hi,
I was build a sample example using python. I tried to update token number by using object rather than global variable. 

```Python
#Python Example

def Step(k):
	p7=FindPlace("P7")
	p2=FindPlace("P2")
	if p2.Tokens >=10:
		p6.Tokens=1
		print "p2=",p2.Tokens," Tokens"
	
def Reset():
	print "Simulation Ended..."
```

The problem is Token can be read but is not updated.  I uploaded the [file](https://ufile.io/08d17) created

**Comment by isindicic** [comment]
It was an nice "old fashion" bug.. .
Tokens was updated well during execution of Step code, but after that those value was overwritten by global variable value.. 

Now I fixed that on the way that global variable update number of tokens but **only if** value in that global variable after execution of Step code is different from value before execution of Step code. 

Updated version of simulator can be taken from release tab.
