### ISSUE TITLE
Latest release is not uploaded to releases

### ISSUE THREAD

**Issue by wbadry** [larics/Petri.Net#6]
Hi Dr. @isindicic ,
(Version:2.1.6163.19399) is not updated. The release has the older version signature (both for .NET 2.0 and 4.0 don't have latest release).
![alt text](https://s16.postimg.org/4wd9wwhg5/2016_11_24_23_09_05.png)

**Comment by isindicic** [comment]
Hi

It was true that I didn't updated version for .NET 4.0 (updated now), but version for .NET 2.0 was already up to date. Can you check again ?
